### ISSUE TITLE
SensorFusion Example

### ISSUE THREAD

**Issue by filmo** [simondlevy/TinyEKF#10]
Is Line 50 correct ???

            hx[2] = this->x[1]; // LM35 temperature from previous state

Should it be (index 2 for LM35) ???:

            hx[2] = this->x[2]; // LM35 temperature from previous state

**Comment by simondlevy** [comment]
No, there is no x[2], because there are only two state variables (x[0]=pressure and x[1]=temperature).   What I'm doing in lines 49-50 is a simple linear approximation to the measurement function h().  

A more realistic implementation might use different computations for hx[1] and hx[2], making it clearer how the EKF works; for example:

  hx[1] = 1.005 * this->x[1]
  hx[2] = .9987 * this->x[1] + .001;

Think of x[1] as the "true" temperature, hx[1] as the temperature value that the baro reads, and and hx[2] as the temperature value that the LM35 reads.  Having two temperature sensors (baro, LM35) and one temperature value (x[1]) is what we mean by "sensor fusion".

**Comment by filmo** [comment]
Got it. Thanks for the clarification.
