### ISSUE TITLE
Delta t Variable in Model Method

### ISSUE THREAD

**Issue by smorad** [simondlevy/TinyEKF#12]
I may be reading this wrong, but I don't see a delta t passed to the model method. I'm trying to find the position using the previous velocity is integrated with respect to dt: `Fx[0] = this->x[0] + this->x[1]*dt`. In this case position is the zero index and velocity is the one index.

I must be missing something, am I supposed to pass delta t via the state vector?

**Comment by simondlevy** [comment]
For EKF you're supposed to come up with your own model (prediction) equation f(x) which in your case would include your own dt constant.  Since the EKF algorthm itself does not use such constants, it would make no sense to pass them as arguments. You may want to read my tutorial to see the reasoning  behind this: https://home.wlu.edu/~levys/kalman_tutorial/
