### ISSUE TITLE
Asynchronous sensor readings

### ISSUE THREAD

**Issue by Freefly18** [simondlevy/TinyEKF#14]
Great tutorial and codebase Simon. It cleared up quite a bit of the concepts behind an EKF.

I am seeing some limitations with TinyEKF and I would like to know if this is right:

- The filter cannot handle null data. If new measurements are received for only one sensor, we can either filter using old data for the other sensor (making it appear as if it was new data that just happened to be exactly the same), or wait until we have new data for each sensor.

- The filter cannot handle variable timesteps. The measurement function is not based on any timestamps and I assume needs to be hardcoded for a specific timestep.

To be clearer, I was planning on using this filter to fuse orientation data coming from 2 sensors at different rates. I can deal with a fixed timestep, but reusing old data for the slower sensor is problematic, as well as waiting for it to update.

**Comment by simondlevy** [comment]
Thanks, and I agree -- those are definite limitations!  Unfortunately, the one that concerns you less (timestep) would be more easily fixed (by passing the current time from your microcontroller), and the one that you really need (updating at different rates for different sensors) would require more work.  This [example](https://github.com/rblilja/AltitudeKF) shows how you can use a standard (linear) KF to treat one sensor (sonar/barometer) as the prediction, and another, faster sensor (accelerometer) as the update.  But incorporating that kind of capability into TinyEKF is beyond what I have time/confidence for at this point.

**Comment by Freefly18** [comment]
I understand. I'll look into my options and I'll report back if I can get something working with async sensors.

**Comment by WCBru** [comment]
I think I have a solution for async sensors, though I'm not completely sure the results indicate that it works.

Instead of having one model with all the observations, it should be possible to use multiple models with fewer observations, but are called depending on the sensor used. So if you have two sensors which update two different states at different times, you implement two models in a filter with 1 observation. The model used (and subsequently, which state the observation updates) would depend on which sensor's data was received. This would also require more step functions or a way to choose between different models.

If you have sensor data which arrives simultaneously, or a sensor updates multiple states, you do as above, splitting each observation into a different model. The difference is that all but one of the models do not update the predicted state or covariance (all values in the Q matrix are 0, next state is the same as the previous state). When data is received, the model which updates the prediction is called first (to create a predicted state) before the models which do not update the prediction are called.

Again, I'm not entirely sure if this is right, but I think it would work.
