### ISSUE TITLE
TinyEKF For GPS filtering?

### ISSUE THREAD

**Issue by Sivapraveen-Entuple** [simondlevy/TinyEKF#23]
Is that possible to use this library for GPS Coordinates, I'm getting GPS latitude and longitude from my gps module, is that possible to filtered out the noise using this library?

**Comment by vtalpaert** [comment]
I would be interested if you get it to work. I guess you will convert the GPS' lat lon to either UTM coords or local coordinates ?

**Comment by Sivapraveen-Entuple** [comment]
Thanks for your response, I'm just extracting latitude and longitude from the raw gps data using my gps module.

the data im getting from the module is okay but variance and some noise will always be there. That is why I'm looking for this GPS filtering.

I hope you got the point, if not kindly let me know. 

Regards
Sivapraveen S

**Comment by vtalpaert** [comment]
Yes, you could use the Kalman filter for smoothing any values, even in degrees (lat lon).

Since the EKF estimates internally the derivatives (speed and accel), you may want to work with all units in meters instead of degrees. It would then make more sense for you in terms of covariance in m**2, speed in m/s etc instead of unrelatable units degrees**2 etc

Conversions from GPS data to Cartesian coordinates should be included in your standard GPS libraries


Best of luck

**Comment by timarnoldev** [comment]
@Sivapraveen-Entuple 
Did you managed to get it work?

Can you share your Q & R matrices.

Regards

**Comment by Sivapraveen-Entuple** [comment]
> @Sivapraveen-Entuple Did you managed to get it work?
> 
> Can you share your Q & R matrices.
> 
> Regards

Not yet, Needs to implement yet.

**Comment by FangXS-github** [comment]
> Thanks for your response, I'm just extracting latitude and longitude from the raw gps data using my gps module.
> 
> the data im getting from the module is okay but variance and some noise will always be there. That is why I'm looking for this GPS filtering.
> 
> I hope you got the point, if not kindly let me know.
> 
> Regards Sivapraveen S

I have been debugging GPS recently, and I have the same problem as you..
